import Head from "next/head";
import { NextPage } from "next";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title> Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <h1>
            Welcon to <a href="https://nextjs.org">Next.js!</a>
          </h1>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Natus deleniti, facilis dicta explicabo, fuga exercitationem ea ipsum iure tempora eos excepturi suscipit nam dolor incidunt aspernatur. Ex quam placeat quas?
          </p>
        </main>
    </>
  )
}

export default Home